---
title: "Data Replication"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Load in Packages

```{r, message = FALSE}
library(tidyverse)
library(lme4)
library(lmerTest) #gives pvals in lmer summary
library(igraph)
library(tnet)
library(lsmeans)
```

#Specify Functions

```{r}
#This function turns the SRI (association) scores in the dataframe into an association matrix. I needed to do this for plotting the networks. I didn't generalize the function as I am only using it for tehse dpecific datasets.

df_to_matrix=function(df){ 

  names=unique(df$Focal.Letter) #extracts a list of individuals names from the column labels
  num_rows=length(names) #gets number of rows, as this is the number of nights recorded for individuals in this group
  n=1 #This counter just prevents duplicates being calculated (e.g. BA with Akim, and Akim with BA)

  #Set up or matrix:
  mat <- matrix(data=NA,nrow=num_rows, ncol=num_rows)
  diag(mat)=0
  colnames(mat) <- names
  rownames(mat) <- names
  
  #loop through names list and populate matrix:
  for (i in n:num_rows){
    for (j in (n+1):num_rows){ #counter +1 so that we don't get self-pairings (e.g. BA with BA)
      if ((n+1) <= num_rows){ #prevents this value from overshooting the actual length of the name list by 1
        if (nrow(filter(df, (Focal.Letter == names[i]) & (Social.Partner == names[j]))) != 0){ #dyads w/ SRI 0 don't appear
          SRI = filter(df, (Focal.Letter == names[i]) & (Social.Partner == names[j]))$SRI
        } else {
          SRI=0 #if row doesn't appear, means that dyad had an SRI of 0
          }
        mat[i,j]=SRI #fills in matrix index for that dyad
      }
    }
      n=n+1 #increase counter to cycle through every individual
  }
  mat[lower.tri(mat)] = t(mat)[lower.tri(mat)] #the above loop only populates top half of matrix, this makes lower half a mirror image as the edges are not directed
  return(mat)
}
```

```{r, message = FALSE}
#This function just performs intra-class correlation analysis. I have to run it 6 times, so figured a function would be neater.

ICC_perms=function(df, n_perms){
  obs=summary(lmer(P1 ~ P2 + (1|Tub) , data = df[complete.cases(df), ]))$coefficients[2, 1] #gets coef for real data
  perms=numeric(n_perms)
  temp=df[complete.cases(df), ] #gets rid of NAs
  
  for (i in 1:n_perms){
    temp$P1=sample(temp$P1, length(temp$P1), replace = FALSE) #permutes and calculates coefs for shuffled data
    perms[i]=summary(lmer(P1 ~ P2 + (1|Tub) , data = temp))$coefficients[2, 1]
    if (i %% 500==0){
      print(i) #just a counter, since it takes a LONG time to run!
    }
  }
  return(list(obs, perms, n_perms))
  }
```

#Load in Data

```{r}
netPos=read.csv("NetworkPositions_Observed.csv", header = T)
edges=read.csv("SRI_edgelist.csv", header = T)
head(edges)
head(netPos)
```
```{r}
netPos
netPos$Period=as.factor(as.character(netPos$Period))
netPos$Treatment=as.factor(netPos$Treatment)
netPos
```
```{r}
und=filter(netPos, Treatment=="C")
dis=filter(netPos, Treatment=="T")
```

```{r}
und_strength=spread(und[,c(1,4,7,10)], Period, strength)
und_betweenness=spread(und[,c(1,5,7,10)], Period, betweenness)
und_clust=spread(und[,c(1,6,7,10)], Period, Clustering.coefficient)

dis_strength=spread(dis[,c(1,4,7,10)], Period, strength)
dis_betweenness=spread(dis[,c(1,5,7,10)], Period, betweenness)
dis_clust=spread(dis[,c(1,6,7,10)], Period, Clustering.coefficient)

colnames(und_strength)[3:4] <- c("P1", "P2")
colnames(und_betweenness)[3:4] <- c("P1", "P2")
colnames(und_clust)[3:4] <- c("P1", "P2")
colnames(dis_strength)[3:4] <- c("P1", "P2")
colnames(dis_betweenness)[3:4] <- c("P1", "P2")
colnames(dis_clust)[3:4] <- c("P1", "P2")


dis_clust
#summary(aov(P1 ~ P2/Tub+Focal.Letter.ID:Tub, data=strength))
```

#See if ICC signifivcant for undisturbed networks:

```{r, message = FALSE}
ICC_und_strength=ICC_perms(und_strength, 1000)

hist(ICC_und_strength[[2]], breaks=50, xlim=c(-1, 1))
abline(v=ICC_und_strength[[1]], col='red')
sum(ICC_und_strength[[2]] > ICC_und_strength[[1]])/(ICC_und_strength[[3]])
#sig
```
```{r, message = FALSE}
ICC_und_betweenness=ICC_perms(und_betweenness, 1000)

hist(ICC_und_betweenness[[2]], breaks=50, xlim=c(-1, 1))
abline(v=ICC_und_betweenness[[1]], col='red')
sum(ICC_und_betweenness[[2]] > ICC_und_betweenness[[1]])/(ICC_und_betweenness[[3]])
#sig
```
```{r, message = FALSE}
ICC_und_clust=ICC_perms(und_clust, 1000)

hist(ICC_und_clust[[2]], breaks=50, xlim=c(-1, 1))
abline(v=ICC_und_clust[[1]], col='red')
sum(ICC_und_clust[[2]] > ICC_und_clust[[1]])/(ICC_und_clust[[3]])
#non-sig
```

#See if ICC signifivcant for disturbed networks:

```{r, message = FALSE}
ICC_dis_strength=ICC_perms(dis_strength, 1000)

hist(ICC_dis_strength[[2]], breaks=50, xlim=c(-1, 1))
abline(v=ICC_dis_strength[[1]], col='red')
sum(ICC_dis_strength[[2]] > ICC_dis_strength[[1]])/(ICC_dis_strength[[3]])
```
```{r, message = FALSE}
ICC_dis_betweenness=ICC_perms(dis_betweenness, 1000)

hist(ICC_dis_betweenness[[2]], breaks=50, xlim=c(-1, 1))
abline(v=ICC_dis_betweenness[[1]], col='red')
sum(ICC_dis_betweenness[[2]] > ICC_dis_betweenness[[1]])/(ICC_dis_betweenness[[3]])
```
```{r, message = FALSE}
ICC_dis_clust=ICC_perms(dis_clust, 1000)

hist(ICC_dis_clust[[2]], breaks=50, xlim=c(-1, 1))
abline(v=ICC_dis_clust[[1]], col='red')
sum(ICC_dis_clust[[2]] > ICC_dis_clust[[1]])/(ICC_dis_clust[[3]])
```



#Visualize Undisturbed Networks at both time points:

```{r}
C1_1_graph=filter(edges, (Group.ID.Populations=="C1") & (Treatment.Period == 1)) %>% 
  df_to_matrix() %>% 
  graph.adjacency(mode="undirected", weighted=T) #%>%
E(C1_1_graph)$width <- (E(C1_1_graph)$weight)*50 #%>%#just an arbitrary number to make weights visibly differentiable
V(C1_1_graph)$color <- "lightblue"

C1_2_graph=filter(edges, (Group.ID.Populations=="C1") & (Treatment.Period == 2)) %>% 
  df_to_matrix() %>% 
  graph.adjacency(mode="undirected", weighted=T) #%>%
E(C1_2_graph)$width <- (E(C1_2_graph)$weight)*50 

C2_1_graph=filter(edges, (Group.ID.Populations=="C2") & (Treatment.Period == 1)) %>% 
  df_to_matrix() %>% 
  graph.adjacency(mode="undirected", weighted=T) #%>%
E(C2_1_graph)$width <- (E(C2_1_graph)$weight)*50 
V(C2_1_graph)$color <- "lightblue"

C2_2_graph=filter(edges, (Group.ID.Populations=="C2") & (Treatment.Period == 2)) %>% 
  df_to_matrix() %>% 
  graph.adjacency(mode="undirected", weighted=T) #%>%
E(C2_2_graph)$width <- (E(C2_2_graph)$weight)*50 

C3_1_graph=filter(edges, (Group.ID.Populations=="C3") & (Treatment.Period == 1)) %>% 
  df_to_matrix() %>% 
  graph.adjacency(mode="undirected", weighted=T) #%>%
E(C3_1_graph)$width <- (E(C3_1_graph)$weight)*50 
V(C3_1_graph)$color <- "lightblue"

C3_2_graph=filter(edges, (Group.ID.Populations=="C3") & (Treatment.Period == 2)) %>% 
  df_to_matrix() %>% 
  graph.adjacency(mode="undirected", weighted=T) #%>%
E(C3_2_graph)$width <- (E(C3_2_graph)$weight)*50 

C4_1_graph=filter(edges, (Group.ID.Populations=="C4") & (Treatment.Period == 1)) %>% 
  df_to_matrix() %>% 
  graph.adjacency(mode="undirected", weighted=T) #%>%
E(C4_1_graph)$width <- (E(C4_1_graph)$weight)*50 
V(C4_1_graph)$color <- "lightblue"

C4_2_graph=filter(edges, (Group.ID.Populations=="C4") & (Treatment.Period == 2)) %>% 
  df_to_matrix() %>% 
  graph.adjacency(mode="undirected", weighted=T) #%>%
E(C4_2_graph)$width <- (E(C4_2_graph)$weight)*50

```
```{r, fig.width = 10, fig.height = 16}
par(mfrow=c(4,2))
plot(C1_1_graph, edge.curved=F,vertex.label=NA)#, layout_with_kk(C1_1_graph))
title("Undisturbed C1, Time 1")
plot(C1_2_graph, edge.curved=F, vertex.label=NA)#, layout_with_kk(C1_2_graph))
title("Undisturbed C1, Time 2")
plot(C2_1_graph, edge.curved=F, vertex.label=NA)#, layout_with_kk(C2_1_graph))
title("Undisturbed C2, Time 1")
plot(C2_2_graph, edge.curved=F, vertex.label=NA)#, layout_with_kk(C2_2_graph))
title("Undisturbed C2, Time 2")
plot(C3_1_graph, edge.curved=F,vertex.label=NA)#, layout_with_kk(C3_1_graph))
title("Undisturbed C3, Time 1")
plot(C3_2_graph, edge.curved=F, vertex.label=NA)#, layout_with_kk(C3_2_graph))
title("Undisturbed C3, Time 2")
plot(C4_1_graph, edge.curved=F, vertex.label=NA)#, layout_with_kk(C4_1_graph))
title("Undisturbed C4, Time 1")
plot(C4_2_graph, edge.curved=F, vertex.label=NA)#, layout_with_kk(C4_2_graph))
title("Undisturbed C4, Time 2")
```

#Visualize Disturbed Networks at both time points:

```{r}
T1_1_graph=filter(edges, (Group.ID.Populations=="T1") & (Treatment.Period == 1)) %>% 
  df_to_matrix() %>% 
  graph.adjacency(mode="undirected", weighted=T) #%>%
E(T1_1_graph)$width <- (E(T1_1_graph)$weight)*50 #%>%#just an arbitrary number to make weights visibly differentiable
V(T1_1_graph)$color <- "lightblue"

T1_2_graph=filter(edges, (Group.ID.Populations=="T1") & (Treatment.Period == 2)) %>% 
  df_to_matrix() %>% 
  graph.adjacency(mode="undirected", weighted=T) #%>%
E(T1_2_graph)$width <- (E(T1_2_graph)$weight)*50 

T2_1_graph=filter(edges, (Group.ID.Populations=="T2") & (Treatment.Period == 1)) %>% 
  df_to_matrix() %>% 
  graph.adjacency(mode="undirected", weighted=T) #%>%
E(T2_1_graph)$width <- (E(T2_1_graph)$weight)*50 
V(T2_1_graph)$color <- "lightblue"

T2_2_graph=filter(edges, (Group.ID.Populations=="T2") & (Treatment.Period == 2)) %>% 
  df_to_matrix() %>% 
  graph.adjacency(mode="undirected", weighted=T) #%>%
E(T2_2_graph)$width <- (E(T2_2_graph)$weight)*50 

T3_1_graph=filter(edges, (Group.ID.Populations=="T3") & (Treatment.Period == 1)) %>% 
  df_to_matrix() %>% 
  graph.adjacency(mode="undirected", weighted=T) #%>%
E(T3_1_graph)$width <- (E(T3_1_graph)$weight)*50 
V(T3_1_graph)$color <- "lightblue"

T3_2_graph=filter(edges, (Group.ID.Populations=="T3") & (Treatment.Period == 2)) %>% 
  df_to_matrix() %>% 
  graph.adjacency(mode="undirected", weighted=T) #%>%
E(T3_2_graph)$width <- (E(T3_2_graph)$weight)*50 

T4_1_graph=filter(edges, (Group.ID.Populations=="T4") & (Treatment.Period == 1)) %>% 
  df_to_matrix() %>% 
  graph.adjacency(mode="undirected", weighted=T) #%>%
E(T4_1_graph)$width <- (E(T4_1_graph)$weight)*50 
V(T4_1_graph)$color <- "lightblue"

T4_2_graph=filter(edges, (Group.ID.Populations=="T4") & (Treatment.Period == 2)) %>% 
  df_to_matrix() %>% 
  graph.adjacency(mode="undirected", weighted=T) #%>%
E(T4_2_graph)$width <- (E(T4_2_graph)$weight)*50

```
```{r, fig.width = 10, fig.height = 16}
par(mfrow=c(4,2))
plot(T1_1_graph, edge.curved=F,vertex.label=NA)#, layout_with_kk(T1_1_graph))
title("Disturbed T1, Time 1")
plot(T1_2_graph, edge.curved=F, vertex.label=NA)#, layout_with_kk(T1_2_graph))
title("Disturbed T1, Time 2")
plot(T2_1_graph, edge.curved=F, vertex.label=NA)#, layout_with_kk(T2_1_graph))
title("Disturbed T2, Time 1")
plot(T2_2_graph, edge.curved=F, vertex.label=NA)#, layout_with_kk(T2_2_graph))
title("Disturbed T2, Time 2")
plot(T3_1_graph, edge.curved=F,vertex.label=NA)#, layout_with_kk(T3_1_graph))
title("Disturbed T3, Time 1")
plot(T3_2_graph, edge.curved=F, vertex.label=NA)#, layout_with_kk(T3_2_graph))
title("Disturbed T3, Time 2")
plot(T4_1_graph, edge.curved=F, vertex.label=NA)#, layout_with_kk(T4_1_graph))
title("Disturbed T4, Time 1")
plot(T4_2_graph, edge.curved=F, vertex.label=NA)#, layout_with_kk(T4_2_graph))
title("Disturbed T4, Time 2")
```




```{r}
filter(netPos, TubPeriod=="C1_1")
paste(strength(C1_graph)* 4.938578)
paste(betweenness(C1_graph))

cor.test(strength(C1_graph),filter(netPos, TubPeriod=="C1_1")$strength)


#cor.test(betweenness(C1_graph),filter(netPos, TubPeriod=="C1_1")$betweenness)
#cor.test(strength(C1_graph),filter(netPos, TubPeriod=="C1_1")$strength)
```
```{r}
#gets correct numbers
#Strange issue with weights; their numbers differ, and seem to have been multiplied by about 5
degree_w(C1_mat,measure=c("degree","output"), type="out", alpha=0.5) #They seem to have multipled this by about 5...
betweenness_w(C1_mat, directed=NULL, alpha=1)
clustering_local_w(C1_mat, measure = "am")


#netPos
```

#Strength Permutations:

```{r}
#get observed coefficients
obs_c2s=summary(lmer(strength~Treatment*Period+Sex+Elytra+Number.of.observations + (1|Focal.Letter.ID) + (1|Tub), data = netPos))$coefficients[2, 1]
obs_c3s=summary(lmer(strength~Treatment*Period+Sex+Elytra+Number.of.observations + (1|Focal.Letter.ID) + (1|Tub), data = netPos))$coefficients[3, 1]
obs_c4s=summary(lmer(strength~Treatment*Period+Sex+Elytra+Number.of.observations + (1|Focal.Letter.ID) + (1|Tub), data = netPos))$coefficients[4, 1]
obs_c5s=summary(lmer(strength~Treatment*Period+Sex+Elytra+Number.of.observations + (1|Focal.Letter.ID) + (1|Tub), data = netPos))$coefficients[5, 1]
obs_c6s=summary(lmer(strength~Treatment*Period+Sex+Elytra+Number.of.observations + (1|Focal.Letter.ID) + (1|Tub), data = netPos))$coefficients[6, 1]
obs_c7s=summary(lmer(strength~Treatment*Period+Sex+Elytra+Number.of.observations + (1|Focal.Letter.ID) + (1|Tub), data = netPos))$coefficients[7, 1]

```
```{r, message = FALSE}
#Get permuted distributions
n_perms=1000
perms_C2s=numeric(n_perms)
perms_C3s=numeric(n_perms)
perms_C4s=numeric(n_perms)
perms_C5s=numeric(n_perms)
perms_C6s=numeric(n_perms)
perms_C7s=numeric(n_perms)

for (i in 1:n_perms){
  temp=netPos[complete.cases(netPos), ]
  temp$strength=sample(temp$strength, length(temp$strength), replace = FALSE)
  summ=summary(lmer(strength~Treatment*Period+Sex+Elytra+Number.of.observations + (1|Focal.Letter.ID) + (1|Tub), data = temp))
  perms_C2s[i]=summ$coefficients[2, 1]
  perms_C3s[i]=summ$coefficients[3, 1]
  perms_C4s[i]=summ$coefficients[4, 1]
  perms_C5s[i]=summ$coefficients[5, 1]
  perms_C6s[i]=summ$coefficients[6, 1]
  perms_C7s[i]=summ$coefficients[7, 1]
  if (i %% 100==0){
      print(i)}
}
```
```{r}
hist(perms_C2s, breaks=50, xlim=c(-1, 1))
abline(v=obs_c2s, col='red')
sum(perms_C2s > obs_c2s)/n_perms
```
```{r}
hist(perms_C3s, breaks=50, xlim=c(-1, 1))
abline(v=obs_c3s, col='red')
sum(perms_C3s > obs_c3s)/n_perms
```
```{r}
hist(perms_C4s, breaks=50, xlim=c(-1, 1))
abline(v=obs_c4s, col='red')
sum(perms_C4s < obs_c4s)/n_perms
```
```{r}
hist(perms_C5s, breaks=50, xlim=c(-1, 1))
abline(v=obs_c5s, col='red')
sum(perms_C5s < obs_c5s)/n_perms
```
```{r}
hist(perms_C6s, breaks=50, xlim=c(-1, 1))
abline(v=obs_c6s, col='red')
sum(perms_C6s > obs_c6s)/n_perms
```
```{r}
hist(perms_C7s, breaks=50, xlim=c(-1, 1))
abline(v=obs_c7s, col='red')
sum(perms_C7s < obs_c7s)/n_perms
```

```{r}
#3,4,6,7
summary(lmer(strength~Treatment*Period+Sex+Elytra+Number.of.observations + (1|Focal.Letter.ID) + (1|Tub), data = netPos))
```


#Betweenness Perms
```{r}
#get observed coefficients
obs_c2b=summary(lmer(betweenness~Treatment*Period+Sex+Elytra+Number.of.observations + (1|Focal.Letter.ID) + (1|Tub), data = netPos))$coefficients[2, 1]
obs_c3b=summary(lmer(betweenness~Treatment*Period+Sex+Elytra+Number.of.observations + (1|Focal.Letter.ID) + (1|Tub), data = netPos))$coefficients[3, 1]
obs_c4b=summary(lmer(betweenness~Treatment*Period+Sex+Elytra+Number.of.observations + (1|Focal.Letter.ID) + (1|Tub), data = netPos))$coefficients[4, 1]
obs_c5b=summary(lmer(betweenness~Treatment*Period+Sex+Elytra+Number.of.observations + (1|Focal.Letter.ID) + (1|Tub), data = netPos))$coefficients[5, 1]
obs_c6b=summary(lmer(betweenness~Treatment*Period+Sex+Elytra+Number.of.observations + (1|Focal.Letter.ID) + (1|Tub), data = netPos))$coefficients[6, 1]
obs_c7b=summary(lmer(betweenness~Treatment*Period+Sex+Elytra+Number.of.observations + (1|Focal.Letter.ID) + (1|Tub), data = netPos))$coefficients[7, 1]

```
```{r, message = FALSE}
#Get permuted distributions
n_perms=1000
perms_C2b=numeric(n_perms)
perms_C3b=numeric(n_perms)
perms_C4b=numeric(n_perms)
perms_C5b=numeric(n_perms)
perms_C6b=numeric(n_perms)
perms_C7b=numeric(n_perms)

for (i in 1:n_perms){
  temp=netPos[complete.cases(netPos), ]
  temp$strength=sample(temp$betweenness, length(temp$betweenness), replace = FALSE)
  summ=summary(lmer(strength~Treatment*Period+Sex+Elytra+Number.of.observations + (1|Focal.Letter.ID) + (1|Tub), data = temp))
  perms_C2b[i]=summ$coefficients[2, 1]
  perms_C3b[i]=summ$coefficients[3, 1]
  perms_C4b[i]=summ$coefficients[4, 1]
  perms_C5b[i]=summ$coefficients[5, 1]
  perms_C6b[i]=summ$coefficients[6, 1]
  perms_C7b[i]=summ$coefficients[7, 1]
  if (i %% 100==0){
      print(i)}
}
```
```{r}
hist(perms_C2b, breaks=50, xlim=c(-1, 1))
abline(v=obs_c2b, col='red')
sum(perms_C2b > obs_c2b)/n_perms
```
```{r}
hist(perms_C3b, breaks=50, xlim=c(-1, 1))
abline(v=obs_c3b, col='red')
sum(perms_C3b > obs_c3b)/n_perms
```
```{r}
hist(perms_C4b, breaks=50, xlim=c(-1, 1))
abline(v=obs_c4b, col='red')
sum(perms_C4b < obs_c4b)/n_perms
```
```{r}
hist(perms_C5b, breaks=50, xlim=c(-1, 1))
abline(v=obs_c5b, col='red')
sum(perms_C5b < obs_c5b)/n_perms
```
```{r}
hist(perms_C6b, breaks=50, xlim=c(-1, 1))
abline(v=obs_c6b, col='red')
sum(perms_C6b > obs_c6b)/n_perms
```
```{r}
hist(perms_C7b, breaks=50, xlim=c(-1, 1))
abline(v=obs_c7b, col='red')
sum(perms_C7b < obs_c7b)/n_perms
```




#BClustering Perms
```{r}
#get observed coefficients
obs_c2c=summary(lmer(Clustering.coefficient~Treatment*Period+Sex+Elytra+Number.of.observations + (1|Focal.Letter.ID) + (1|Tub), data = netPos))$coefficients[2, 1]
obs_c3c=summary(lmer(Clustering.coefficient~Treatment*Period+Sex+Elytra+Number.of.observations + (1|Focal.Letter.ID) + (1|Tub), data = netPos))$coefficients[3, 1]
obs_c4c=summary(lmer(Clustering.coefficient~Treatment*Period+Sex+Elytra+Number.of.observations + (1|Focal.Letter.ID) + (1|Tub), data = netPos))$coefficients[4, 1]
obs_c5c=summary(lmer(Clustering.coefficient~Treatment*Period+Sex+Elytra+Number.of.observations + (1|Focal.Letter.ID) + (1|Tub), data = netPos))$coefficients[5, 1]
obs_c6c=summary(lmer(Clustering.coefficient~Treatment*Period+Sex+Elytra+Number.of.observations + (1|Focal.Letter.ID) + (1|Tub), data = netPos))$coefficients[6, 1]
obs_c7c=summary(lmer(Clustering.coefficient~Treatment*Period+Sex+Elytra+Number.of.observations + (1|Focal.Letter.ID) + (1|Tub), data = netPos))$coefficients[7, 1]

```
```{r, message = FALSE}
#Get permuted distributions
n_perms=1000
perms_C2c=numeric(n_perms)
perms_C3c=numeric(n_perms)
perms_C4c=numeric(n_perms)
perms_C5c=numeric(n_perms)
perms_C6c=numeric(n_perms)
perms_C7c=numeric(n_perms)

for (i in 1:n_perms){
  temp=netPos[complete.cases(netPos), ]
  temp$strength=sample(temp$Clustering.coefficient, length(temp$Clustering.coefficient), replace = FALSE)
  summ=summary(lmer(strength~Treatment*Period+Sex+Elytra+Number.of.observations + (1|Focal.Letter.ID) + (1|Tub), data = temp))
  perms_C2c[i]=summ$coefficients[2, 1]
  perms_C3c[i]=summ$coefficients[3, 1]
  perms_C4c[i]=summ$coefficients[4, 1]
  perms_C5c[i]=summ$coefficients[5, 1]
  perms_C6c[i]=summ$coefficients[6, 1]
  perms_C7c[i]=summ$coefficients[7, 1]
  if (i %% 100==0){
      print(i)}
}
```
```{r}
hist(perms_C2c, breaks=50, xlim=c(-1, 1))
abline(v=obs_c2c, col='red')
sum(perms_C2c > obs_c2c)/n_perms
```
```{r}
hist(perms_C3c, breaks=50, xlim=c(-1, 1))
abline(v=obs_c3c, col='red')
sum(perms_C3c > obs_c3c)/n_perms
```
```{r}
hist(perms_C4c, breaks=50, xlim=c(-1, 1))
abline(v=obs_c4c, col='red')
sum(perms_C4c < obs_c4c)/n_perms
```
```{r}
hist(perms_C5c, breaks=50, xlim=c(-1, 1))
abline(v=obs_c5c, col='red')
sum(perms_C5c < obs_c5c)/n_perms
```
```{r}
hist(perms_C6c, breaks=50, xlim=c(-1, 1))
abline(v=obs_c6c, col='red')
sum(perms_C6c > obs_c6c)/n_perms
```
```{r}
hist(perms_C7c, breaks=50, xlim=c(-1, 1))
abline(v=obs_c7c, col='red')
sum(perms_C7c < obs_c7c)/n_perms
```

```{r}
s=lmer(strength~Treatment*Period+Sex+Elytra+Number.of.observations + (1|Focal.Letter.ID) + (1|Tub), data = netPos)
b=lmer(betweenness~Treatment*Period+Sex+Elytra+Number.of.observations + (1|Focal.Letter.ID) + (1|Tub), data = netPos)
c=lmer(Clustering.coefficient~Treatment*Period+Sex+Elytra+Number.of.observations + (1|Focal.Letter.ID) + (1|Tub), data = netPos)

lsmeans(s, c("Treatment", "Period"))
lsmeans(b, c("Treatment", "Period"))
lsmeans(c, c("Treatment", "Period"))
```


